---
name: BlazinFly
main: iiFlamiinBlaze\BlazinFly\BlazinFly
description: An advanced survival fly plugin!
version: 1.8.6
api:
- 3.0.0
author: iiFlamiinBlaze
commands:
  fly:
    description: "lệnh chấp nhận bạn có thể bay ở chế độ sinh tồn!"
permissions:
  fly.command:
    description: BlazinFly command permission
    default: op
...
