name: Sell-ByMamChamPlu
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.1.2, 3.0.0, 3.1.4]
main: SellHand\Main
version: 1.3.0
authors: [Muqsit, JackMD, MamChamPlugin]
author: VMPE Development Team
commands:
  sell:
    description: "Bán Đồ Trong Kho Của Bạn"
    permission: sell.command
permissions:
  sell:
    default: true
    children:
      sell.hand:
        default: true
      sell.all:
        default: true
      sell.command:
        default: true
