name: SETVIP
main: MCPEVN\SetVip
version: 2.3
api: 3.0.0
author: MCPEVN TEAM
description: VIP plugin by MCPEVN Team COPYRIGHT
commands:
  grouptime:
    description: set other player's vip status
  grouptimeremove:
    description: remove other player's vip status