---
name: CustomShopUI
main: SaltyPixelDevz\CustomShopUIv2\Shop
version: 4.0.5
api:
- 3.0.0
author: SaltyPixelDevz
website: http://saltypixel.ga
depend:
- EconomyAPI
commands:
  shop:
    description: Open Shops
permissions:
  shop.shop:
    default: true
    description: Allows use of the /shop command
...
