name: AllAPILoader
main: TheNewHEROBRINE\AllAPILoader\Main
version: 2.1.0
api: [3.0.0, 4.0.0]
author: TheNewHEROBRINE
description: Makes the server load every plugin regardless of the API version
load: STARTUP
softdepend: ["DevTools", "FolderPluginLoader"]
