name: Coins
main: "PocketMoney\\PocketMoney"
version: 4.0.1
api: 
 - 3.1.1
 - 3.0.0
 - 3.0.0-ALPHA12
load: "POSTWORLD"
author: "MinecrafterJPN" 
 #edit: Phuongaz
authors: ["MinecrafterJPN"]
description: "The core economy system with many APIs"
website: "https://github.com/MinecrafterJPN/PocketMoney"
commands:
 coin:
  description: "MY COIN"
  usage: "/coin [subcommand]"
  permission: "pocketmoney.money"
 acoin:
   description: "Acoin Command Form"
   default: true
 admincoin:
    description: "ADMIN COIN"
    default: OP
permissions:
 pocketmoney:
  default: "op"
  description: "Allows using everything PocketMoney has"
  children:
  # The following permissions belong to commands
   pocketmoney.money:
    default: true
    description: "Allows using \"/coin\" command"
   pocketmoney.help:
    default: true
    description: "Allows using \"/coin help\" command"
   pocketmoney.view:
    default: true
    description: "Allows using \"/coin view\" command"
   pocketmoney.pay:
    default: true
    description: "Allows using \"/coin pay\" command"
   pocketmoney.top:
    default: true
    description: "Allows using \"/coin top\" command"
