---
# Developed by TheAz928
# VanillaEnchantments configuration file

# Fortune applicable blocks
# Only these blocks will have their drops multiplied
# Format: "name or id"
fortune.blocks:
- leaves
- nether_quartz_ore
- redstone_ore
# Looting applicable entities
looting.entities:
  chicken:
  - "feather" # If drops contain feather, it'll be multiplied

# Version, recommended to not change
version: "1.2.5"

...