---
name: CustomShopUI
main: AlexPads\ShopUI\SaltyPixelDevz\Shop
version: 3.2.1
api:
- 3.3.2
author: TinyPixelDevz
website: saltypixel.ga
depend:
- EconomyAPI
commands:
  shop:
    description: '§c❤§eShop§6Angle§c❤'
...
